services:
  nginx:
    image: nginx
    volumes:
     - ./account-book-front-end/dist/:/usr/share/nginx/html
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    depends_on:
      - server
  server:
    image: node:16.15.0
    ports:
      - 7001:7001
    working_dir: /app/server
    volumes:
      - ./account-book-server:/app/server
    command: sh -c "yarn install && yarn run dev"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: account_book
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - account-book-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: account_book

volumes:
  account-book-mysql-data: